services:
  mkdocs:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: mkdocs
    ports:
      - "8080:80"
    networks: 
      - mkdocs_network
   # volumes: 
     # - ./site:/usr/share/nginx/html

networks: 
  mkdocs_network:
    driver: bridge
