services:
  mkdocs:
    image: nginx:alpine
    container_name: mydocs
    ports:
      - 8080:80
    networks: 
      - mkdocs-network
    volumes: 
      - ./site:/usr/share/nginx/html
networks: 
  mydocs_network:
    driver: bridge
