# Project information
site_name: My MkDocs Project
site_description: "An example MkDocs project using the Material theme"
site_url: "https://jagoum.github.io/mk-docs" # Change this to your site's URL

# Theme settings
theme:
  name: bootstrap

# Navbar settings (site structure)
nav:
  - Home: index.md
  - About: about.md
  - Docker: DK.md
  - Mulipass: multipass.md

# Extra settings
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

# Repository configuration (for the edit link on pages)
repo_name: Jagoum/mk-docs
repo_url: https://github.com/jagoum/mk-docs
edit_uri: edit/main/docs/
